Client restructuring
RaaLabs/TSIClient pull request #40
Opened 2020-08-27 06:51 UTC by maikberthelsen

Restructured the client, and added the new aggregate functions from Gen2. Altered the tests so that it fits with the new structure. Some more tests should maybe be implemented to check the new functions.

2020-08-27 07:00 UTC, rafaelschlatter commented
Awesome :) will go through it.

2020-08-27 07:36 UTC, rafaelschlatter requested changes
Really nice work! Especially the mocks in the fixtures are neat.

I added some comments to the individual files, I think there is some duplicate functionality, and some other minor comments.

2020-08-27 07:36 UTC, rafaelschlatter commented on TSIClient/hierarchies/hierarchies_api.py
> +    def _updateTimeSeries(self, payload, timeseries):
This method should go into the instances api.

2020-08-27 07:36 UTC, rafaelschlatter commented on TSIClient/hierarchies/hierarchies_api.py
> +    def writeHierarchies(self, payload):
It seems like this method is not just writing hierarchies, but rather updating the whole time series instances. Should this be renamed and moved to the instances api as well?

2020-08-27 07:36 UTC, rafaelschlatter commented on TSIClient/hierarchies/hierarchies_api.py
> +    def writeHierarchies(self, payload):
i see it is also present in `instances_api.py`, i guess `writeHierarchies()` and `_updateTimeSeries()` can be deleted here.

2020-08-27 07:36 UTC, rafaelschlatter commented on TSIClient/types/types_api.py
> +    def writeTypes(self, payload):
Same comment here. This seems to be the same functionality as in the `instances_api.py`. Think that can also be deleted.

2020-08-27 07:36 UTC, rafaelschlatter commented on tests/test_tsiclient.py
> +@pytest.fixture
Nice that it works to include mocks in the fixture :)

2020-08-27 07:36 UTC, rafaelschlatter commented on tests/mock_responses.py
> +    oauth_url_from_env = "https://login.microsoftonline.com/{}/oauth2/token".format("my_tenant_id")
Is it possible to use just one url for this? the only difference is "yet_another_tenant_id" and "yet_another_tenant_id".

Same for the `mock_environments_from_env` mock response. I believe if you use the same argument names in both fixtures it can be avoided to have two mock urls and two mock responses.

2020-08-27 07:36 UTC, rafaelschlatter commented on tests/conftest.py
>  @pytest.fixture(scope="module")
Can this file be deleted? Since you have the fixtures in `test_tsiclient.py`?

2020-08-27 07:37 UTC, rafaelschlatter commented on TSIClient/hierarchies/hierarchies_api.py
> +    def _updateTimeSeries(self, payload, timeseries):
Or rather deleted, I saw later that it exists in the `instances_api.py` as well.

2020-08-27 07:40 UTC, maikberthelsen commented on tests/mock_responses.py
> +    oauth_url_from_env = "https://login.microsoftonline.com/{}/oauth2/token".format("my_tenant_id")
I think we could do it all in one yes, but I was wondering if there was a reason for the difference in the responses in order to distinguish them. But if not we could change it so that it works for both.

2020-08-27 07:41 UTC, maikberthelsen commented on tests/conftest.py
>  @pytest.fixture(scope="module")
Yes, it can be deleted.

2020-08-27 08:52 UTC, rafaelschlatter approved these changes
Nice. Nothing to add from my side, can be merged :)

2020-09-04 11:50 UTC, srudaa approved these changes
Great work @maikberthelsen!

2020-09-04 11:52 UTC, merged